# Generated by Django 5.0 on 2023-12-26 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competencia", models.CharField(max_length=50)),
                ("valor", models.IntegerField()),
                ("softskill", models.BooleanField()),
                ("order", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "invalid": "Please enter a valid email address."
                        },
                        max_length=254,
                    ),
                ),
                ("subject", models.CharField(max_length=150)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primeiroNome", models.CharField(max_length=100)),
                ("ultimoNome", models.CharField(max_length=100)),
                ("linkedin", models.URLField(max_length=500)),
                ("outroLink", models.URLField(max_length=500)),
                ("professor", models.BooleanField(default=False)),
                ("aluno", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Mestrado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=500)),
                ("trimestre", models.IntegerField()),
                ("units", models.IntegerField()),
                ("order", models.IntegerField()),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="portfolio.pessoa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=500)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("ects", models.IntegerField()),
                ("ranking", models.IntegerField()),
                ("linklusofona", models.URLField()),
                ("order", models.IntegerField()),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.pessoa",
                    ),
                ),
                (
                    "professorAuxiliar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="portfolio.pessoa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=500)),
                ("linkGit", models.URLField(max_length=500)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField(blank=True)),
                ("trimestre", models.IntegerField(blank=True)),
                ("imagem", models.ImageField(upload_to="")),
                ("tecnologia", models.CharField(max_length=100)),
                ("video", models.URLField(blank=True)),
                ("left", models.BooleanField(default=False)),
                ("right", models.BooleanField(default=False)),
                ("mestrado", models.BooleanField(default=False)),
                ("licenciatura", models.BooleanField(default=False)),
                ("order", models.IntegerField()),
                (
                    "cadeira",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.licenciatura",
                    ),
                ),
                (
                    "competencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="portfolio.competencia",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.mestrado",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="portfolio.pessoa",
                    ),
                ),
            ],
        ),
    ]
