# Generated by Django 5.0 on 2023-12-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "invalid": "Please enter a valid email address."
                        },
                        max_length=254,
                    ),
                ),
                ("subject", models.CharField(max_length=150)),
                ("message", models.TextField()),
            ],
        ),
    ]
